### ISSUE TITLE
Contextual Menu Items do not appear for files on non-boot volumes

### ISSUE THREAD

**Issue by gordon8214** [knurling/ServiceStation#2]
Service Station contextual menu items don't appear for files or folders on any volumes except my boot volume, despite adding other volumes under "Service Station Finder Locations."

Catalina 10.15.4 (19E287)

**Comment by pkamb** [comment]
Thanks for opening. This is a current limitation of the app.

I'm going to try to support additional volumes in one of the next updates.

**Comment by bomberstudios** [comment]
Ditto for networked volumes (which are probably included in the “non-boot volumes” group, but I thought I’d mention it)

Thanks for this great tool!

**Comment by FabSugoi** [comment]
Bought the app today to try some script launch only to realize networked volumes were not available… I'll not ask for refund because I think this app is the missing link for users that want to do file treatments from the contextual menu and I want to support it. I hope external volumes will be added soon.

**Comment by pkamb** [comment]
Sorry, did not mean to close this.

Mounted Volumes and Network Drives support has been added in upcoming version 2020.5.

However, I'm running into some App Review trouble. Apple wants changes to some things that previously were released. I need to make a few adjustments before I can release 2020.5. Sorry for the delay.

**Comment by gingerbeardman** [comment]
Interested to know more!

**Comment by pkamb** [comment]
Mounted and Network Volume has been added today in v2020.5, which is now available on the Mac App Store.

You will need to add a new Finder Location for each mounted volume. I know this is annoying; sorry. I don't believe there's a better way due to sandboxing.

Please let me know how it works for you! Thanks.

**Comment by gordon8214** [comment]
Thanks! Any consideration to offering a version of this app outside the App Store, without sandboxing?

**Comment by pkamb** [comment]
@gordon8214 No plans for that at this time. I'll continue to investigate if there's a better/easier way to specify sandbox bookmarks for all Volumes.

**Comment by FabSugoi** [comment]
Working like a charm on mounted volumes so far, thanks a lot for your work !
