### ISSUE TITLE
Bug: Add Script option no longer functions

### ISSUE THREAD

**Issue by gingerbeardman** [knurling/ServiceStation#21]
I had previously added a script to the context menu. 
But I can no longer add a script.

1. Click `+` icon in Menu Item column
1. Click `Add Script` option

Expected
- should do something

Actual 
- does nothing

Version 2020.3 (14)

No messages in console

**Comment by gingerbeardman** [comment]
Workaround: https://github.com/knurling/ServiceStation/issues/20#issuecomment-617885177

**Comment by pkamb** [comment]
In version 2020.4 I'm now restarting the background process every time the main app is launched:

    SMLoginItemSetEnabled(attendantBundleID, false) // added in 2020.4
    SMLoginItemSetEnabled(attendantBundleID, true)

This should kill the previous version of the attendant, if it's already running, and re-launch the newest version from the updated app bundle. This should happen quickly in the background and be entirely invisible to the user.

Please let me know if you continue to see any non-functioning buttons or communication to the attendant. Or if there are any issues due to the attendant restarting more frequently.
