### ISSUE TITLE
Doesn't Work macOS 10.14.6

### ISSUE THREAD

**Issue by sathomas** [knurling/ServiceStation#42]
Works fine on the test items but nothing in the finder

version 2020.5 (18)

![CleanShot 2020-06-08 at 19 45 45](https://user-images.githubusercontent.com/1731910/84090824-cb6db100-a9c0-11ea-8ebd-90e1d182eb06.png)

![CleanShot 2020-06-08 at 19 46 09](https://user-images.githubusercontent.com/1731910/84090825-cdd00b00-a9c0-11ea-8c8c-60f8921a46a0.png)

 
![CleanShot 2020-06-08 at 19 48 09](https://user-images.githubusercontent.com/1731910/84090948-14be0080-a9c1-11ea-962e-189c2d2bb832.png)

![CleanShot 2020-06-08 at 19 48 19](https://user-images.githubusercontent.com/1731910/84090956-1b4c7800-a9c1-11ea-9e3d-1e26de9c7953.png)

**Comment by pkamb** [comment]
Despite being enabled in System Preferences, the Service Station Finder Extension does not appear to be running.

Please filter for `Service Station` in Activity Monitor and see which processes are running.

This usually will sort itself out after some amount of time. Logging out and back in or restarting Finder may also help. Sorry for the inconvenience.

Has it started working since opening this ticket? Or still no menu items?

**Comment by sathomas** [comment]
Well, sorting itself out over time didn’t do the trick. It took be about a week to get around to reporting the issue and it was broken the entire week.

But…

Force restart of Finder did. So it is working now

**Comment by pkamb** [comment]
Good to hear, and sorry for the problem. I'll add restarting Finder to the FAQ for this kind of issue.
